language: python
python:
  - "3.6"


before_script:
  - psql -c 'create database welobim;' -U postgres

services:
  - postgresql

install:
  - pip install -r requirements.txt


script:
  - python manage.py test && flake8